name: Build Koeur APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Compiler Koeur
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v5

      - name: Installer Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Vérifier Java
        run: java -version

      - name: Vérifier Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew --version

      - name: Nettoyer le projet
        run: |
          ./gradlew clean --no-daemon

      - name: Compiler l'APK Debug
        run: |
          ./gradlew :app:assembleDebug \
            --stacktrace \
            --no-daemon

      - name: Vérifier que l'APK existe
        run: |
          test -f app/build/outputs/apk/debug/app-debug.apk
          ls -lh app/build/outputs/apk/debug/app-debug.apk

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: koeur-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
